### ISSUE TITLE
Change the JSON storage of stock values

### ISSUE THREAD

**Issue by Aryan470** [Aryan470/StockCog#3]
```
"stocks" : [
    {"FOXY": "1000"},
    {"SEBC": "1100"}
]
```

should be

```
"stocks" : {
    "FOXY": "1000",
    "SEBC": "1100"
}
```
So fix the methods using it and the file itself

**Comment by sebastienvercammen** [comment]
Alternatively, continue using an array as intended, but rework the objects (and don't store numbers as strings):

```
"stocks": [{
    "name": "FOXY INDUSTRIES",
    "ticker": "FOXY",
    "value": 1000
}, {
    "name": "SEB CORPORATION",
    "ticker": "SEBC",
    "value": 1100
}]
```

This would be a more sensible approach if you ever want to allow a more real-life situation, where you don't have just two stocks, and where the stocks on the market is dynamic (i.e. companies can go public).

**Comment by Aryan470** [comment]
Oki

**Comment by Aryan470** [comment]
done 💯 😎
